// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDate) Reset() {
	*x = RequestDate{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDate) ProtoMessage() {}

func (x *RequestDate) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDate.ProtoReflect.Descriptor instead.
func (*RequestDate) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *RequestDate) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ResponseDailyValues struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Date          string                       `protobuf:"bytes,1,opt,name=Date,proto3" json:"Date,omitempty"`
	Name          string                       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Valute        []*ResponseDailyValues_Value `protobuf:"bytes,3,rep,name=Valute,proto3" json:"Valute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseDailyValues) Reset() {
	*x = ResponseDailyValues{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseDailyValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDailyValues) ProtoMessage() {}

func (x *ResponseDailyValues) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDailyValues.ProtoReflect.Descriptor instead.
func (*ResponseDailyValues) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseDailyValues) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ResponseDailyValues) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseDailyValues) GetValute() []*ResponseDailyValues_Value {
	if x != nil {
		return x.Valute
	}
	return nil
}

type ResponseDailyValues_Value struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	ID            string                               `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	MetaValue     *ResponseDailyValues_Value_MetaValue `protobuf:"bytes,2,opt,name=meta_value,json=metaValue,proto3" json:"meta_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseDailyValues_Value) Reset() {
	*x = ResponseDailyValues_Value{}
	mi := &file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseDailyValues_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDailyValues_Value) ProtoMessage() {}

func (x *ResponseDailyValues_Value) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDailyValues_Value.ProtoReflect.Descriptor instead.
func (*ResponseDailyValues_Value) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ResponseDailyValues_Value) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ResponseDailyValues_Value) GetMetaValue() *ResponseDailyValues_Value_MetaValue {
	if x != nil {
		return x.MetaValue
	}
	return nil
}

type ResponseDailyValues_Value_MetaValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumCode       string                 `protobuf:"bytes,1,opt,name=NumCode,proto3" json:"NumCode,omitempty"`
	CharCode      string                 `protobuf:"bytes,2,opt,name=CharCode,proto3" json:"CharCode,omitempty"`
	Nominal       int64                  `protobuf:"varint,3,opt,name=Nominal,proto3" json:"Nominal,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=Value,proto3" json:"Value,omitempty"`
	VunitRate     string                 `protobuf:"bytes,6,opt,name=VunitRate,proto3" json:"VunitRate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseDailyValues_Value_MetaValue) Reset() {
	*x = ResponseDailyValues_Value_MetaValue{}
	mi := &file_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseDailyValues_Value_MetaValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDailyValues_Value_MetaValue) ProtoMessage() {}

func (x *ResponseDailyValues_Value_MetaValue) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDailyValues_Value_MetaValue.ProtoReflect.Descriptor instead.
func (*ResponseDailyValues_Value_MetaValue) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *ResponseDailyValues_Value_MetaValue) GetNumCode() string {
	if x != nil {
		return x.NumCode
	}
	return ""
}

func (x *ResponseDailyValues_Value_MetaValue) GetCharCode() string {
	if x != nil {
		return x.CharCode
	}
	return ""
}

func (x *ResponseDailyValues_Value_MetaValue) GetNominal() int64 {
	if x != nil {
		return x.Nominal
	}
	return 0
}

func (x *ResponseDailyValues_Value_MetaValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseDailyValues_Value_MetaValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ResponseDailyValues_Value_MetaValue) GetVunitRate() string {
	if x != nil {
		return x.VunitRate
	}
	return ""
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\x04ozon\"!\n" +
	"\vRequestDate\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\"\x80\x03\n" +
	"\x13ResponseDailyValues\x12\x12\n" +
	"\x04Date\x18\x01 \x01(\tR\x04Date\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x127\n" +
	"\x06Valute\x18\x03 \x03(\v2\x1f.ozon.ResponseDailyValues.ValueR\x06Valute\x1a\x87\x02\n" +
	"\x05Value\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12H\n" +
	"\n" +
	"meta_value\x18\x02 \x01(\v2).ozon.ResponseDailyValues.Value.MetaValueR\tmetaValue\x1a\xa3\x01\n" +
	"\tMetaValue\x12\x18\n" +
	"\aNumCode\x18\x01 \x01(\tR\aNumCode\x12\x1a\n" +
	"\bCharCode\x18\x02 \x01(\tR\bCharCode\x12\x18\n" +
	"\aNominal\x18\x03 \x01(\x03R\aNominal\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Value\x18\x05 \x01(\tR\x05Value\x12\x1c\n" +
	"\tVunitRate\x18\x06 \x01(\tR\tVunitRate2V\n" +
	"\x15MockDailyValueService\x12=\n" +
	"\rGetDailyValue\x12\x11.ozon.RequestDate\x1a\x19.ozon.ResponseDailyValuesB\x05Z\x03pb/b\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_server_proto_goTypes = []any{
	(*RequestDate)(nil),                         // 0: ozon.RequestDate
	(*ResponseDailyValues)(nil),                 // 1: ozon.ResponseDailyValues
	(*ResponseDailyValues_Value)(nil),           // 2: ozon.ResponseDailyValues.Value
	(*ResponseDailyValues_Value_MetaValue)(nil), // 3: ozon.ResponseDailyValues.Value.MetaValue
}
var file_server_proto_depIdxs = []int32{
	2, // 0: ozon.ResponseDailyValues.Valute:type_name -> ozon.ResponseDailyValues.Value
	3, // 1: ozon.ResponseDailyValues.Value.meta_value:type_name -> ozon.ResponseDailyValues.Value.MetaValue
	0, // 2: ozon.MockDailyValueService.GetDailyValue:input_type -> ozon.RequestDate
	1, // 3: ozon.MockDailyValueService.GetDailyValue:output_type -> ozon.ResponseDailyValues
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
