// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: server.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MockDailyValueService_GetDailyValue_FullMethodName = "/ozon.MockDailyValueService/GetDailyValue"
)

// MockDailyValueServiceClient is the client API for MockDailyValueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MockDailyValueServiceClient interface {
	GetDailyValue(ctx context.Context, in *RequestDate, opts ...grpc.CallOption) (*ResponseDailyValues, error)
}

type mockDailyValueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMockDailyValueServiceClient(cc grpc.ClientConnInterface) MockDailyValueServiceClient {
	return &mockDailyValueServiceClient{cc}
}

func (c *mockDailyValueServiceClient) GetDailyValue(ctx context.Context, in *RequestDate, opts ...grpc.CallOption) (*ResponseDailyValues, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseDailyValues)
	err := c.cc.Invoke(ctx, MockDailyValueService_GetDailyValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MockDailyValueServiceServer is the server API for MockDailyValueService service.
// All implementations must embed UnimplementedMockDailyValueServiceServer
// for forward compatibility.
type MockDailyValueServiceServer interface {
	GetDailyValue(context.Context, *RequestDate) (*ResponseDailyValues, error)
	mustEmbedUnimplementedMockDailyValueServiceServer()
}

// UnimplementedMockDailyValueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMockDailyValueServiceServer struct{}

func (UnimplementedMockDailyValueServiceServer) GetDailyValue(context.Context, *RequestDate) (*ResponseDailyValues, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyValue not implemented")
}
func (UnimplementedMockDailyValueServiceServer) mustEmbedUnimplementedMockDailyValueServiceServer() {}
func (UnimplementedMockDailyValueServiceServer) testEmbeddedByValue()                               {}

// UnsafeMockDailyValueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MockDailyValueServiceServer will
// result in compilation errors.
type UnsafeMockDailyValueServiceServer interface {
	mustEmbedUnimplementedMockDailyValueServiceServer()
}

func RegisterMockDailyValueServiceServer(s grpc.ServiceRegistrar, srv MockDailyValueServiceServer) {
	// If the following call pancis, it indicates UnimplementedMockDailyValueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MockDailyValueService_ServiceDesc, srv)
}

func _MockDailyValueService_GetDailyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockDailyValueServiceServer).GetDailyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockDailyValueService_GetDailyValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockDailyValueServiceServer).GetDailyValue(ctx, req.(*RequestDate))
	}
	return interceptor(ctx, in, info, handler)
}

// MockDailyValueService_ServiceDesc is the grpc.ServiceDesc for MockDailyValueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MockDailyValueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ozon.MockDailyValueService",
	HandlerType: (*MockDailyValueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDailyValue",
			Handler:    _MockDailyValueService_GetDailyValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
